# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.2.401'
  displayName: 'Install .NET Core SDK'

- script: dotnet restore
  displayName: Restore

- script: dotnet build --no-restore --configuration $(buildConfiguration)
  displayName: Build

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    publishTestResults: true
    arguments: '--no-restore'

- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: pack
    nobuild: true
    outputDir: '$(Build.ArtifactStagingDirectory)'
    arguments: '--configuration $(buildConfiguration)'
